spring.application.name=RESTAPIs

#Port configuration
server.port=8081

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/EmployeeDB
spring.datasource.username=postgres
spring.datasource.password=V1shwa@sql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.servlet.context-path=/api